theme: jekyll-theme-minimal
title: Carla Giner Delgado, PhD
description: "Population geneticist interested in structural variation, natural selection, complex traits, recombination and data visualisation (among others)."
logo: assets/img/CarlaGinerDelgado.jpeg
markdown: kramdown
